In [1]:
!pip install numpy

In [2]:
import numpy as np


In [3]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [13]:
 ##lst = [1,2,3] :- 1 dimentional array
 lst = [[1,2,3],
        [1,2,3],
        [1,2,3]]



In [15]:
lst

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [16]:
type(lst)


list

In [17]:
arr = np.array(lst)

In [18]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [19]:
type(arr)

numpy.ndarray

In [20]:
arr.ndim

2

In [21]:
arr.shape

(3, 3)

In [22]:
arr.size

9

In [23]:
arr.dtype

dtype('int64')

In [24]:

zeros = np.zeros((5,3))

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
ones = np.ones((6,3))

In [27]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])