In [1]:
import numpy as np

In [2]:

np.random.random((3,3))

array([[0.30456065, 0.02030551, 0.07056109],
       [0.7085777 , 0.50289764, 0.50590614],
       [0.26258516, 0.25256029, 0.79394558]])

In [3]:
arr = np.random.random((3,3))

In [4]:
np.arange(1,10,3)

array([1, 4, 7])

In [5]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [6]:
arr = np.random.random((4,3))

In [7]:
arr

array([[0.20013812, 0.26775171, 0.85132084],
       [0.12899009, 0.83857359, 0.69755445],
       [0.81057816, 0.36856983, 0.33855102],
       [0.87507336, 0.94091869, 0.68552869]])

In [8]:
arr = np.reshape(arr , (3,4))

In [9]:

arr

array([[0.20013812, 0.26775171, 0.85132084, 0.12899009],
       [0.83857359, 0.69755445, 0.81057816, 0.36856983],
       [0.33855102, 0.87507336, 0.94091869, 0.68552869]])

In [10]:
arr = np.reshape(arr , (6,2))

In [11]:
arr

array([[0.20013812, 0.26775171],
       [0.85132084, 0.12899009],
       [0.83857359, 0.69755445],
       [0.81057816, 0.36856983],
       [0.33855102, 0.87507336],
       [0.94091869, 0.68552869]])

In [12]:
arr.flatten()

array([0.20013812, 0.26775171, 0.85132084, 0.12899009, 0.83857359,
       0.69755445, 0.81057816, 0.36856983, 0.33855102, 0.87507336,
       0.94091869, 0.68552869])