In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
print(arr + 1)
print(arr - 1)
print(arr * 5)
print(arr / 2)
print(arr ** 3)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 5 10 15 20 25 30]
[0.5 1.  1.5 2.  2.5 3. ]
[  1   8  27  64 125 216]


In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
arr = arr + 1

In [7]:
arr


array([2, 3, 4, 5, 6, 7])

In [8]:
arr += 1

In [9]:
arr

array([3, 4, 5, 6, 7, 8])

In [10]:
arr *= 2

In [11]:
arr

array([ 6,  8, 10, 12, 14, 16])

In [12]:
arr.max()

16

In [13]:
arr.min()

6

In [15]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.max(axis = 0) # Max element column-wise

array([7, 8, 9])

In [18]:
arr.max(axis = 1) # Max element row-wise

array([3, 6, 9])

In [19]:
arr.min(axis = 0) # Min element column-wise

array([1, 2, 3])

In [20]:
arr.min(axis = 1) # Min element row-wise

array([1, 4, 7])

In [21]:

arr.sum()

45