In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:

arr[3: ]

array([4, 5, 6, 7, 8])

In [5]:
arr[ : -3]

array([1, 2, 3, 4, 5])

In [6]:

arr[3  :  -3]

array([4, 5])

In [7]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [8]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [9]:
arr[ 3 , 1]

3

In [10]:
arr[ 1: , 1:]

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])