In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[8,7,6,5], [4,3,2,1]])

In [3]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [5]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [6]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [7]:
np.hstack((arr2,arr1))

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

In [8]:
arr = np.concatenate((arr1,arr2), axis = 0)

In [9]:
np.concatenate((arr1,arr2), axis = 1)

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [10]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [11]:
np.hsplit(arr, 2)

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]),
 array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [12]:
np.vsplit(arr, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]